package DataBase;


public enum MessageType {
    SUCCESS,FAIL,
    LOGIN,LOGOUT,REGISTER,
    GROUP_MSG,PRIVATE_MSG,GROUP_MSG_LOG,PRIVATE_MSG_LOG,
    USER_LIST,USER_NAME_LIST,
    GROUP_CREATE,GROUP_DELETE,GROUP_JOIN,GROUP_WITHDRAW,
    SEND_FILE
}